language: python
python:
  - "3.6"

addons:
  firefox: "60.0.1"
  sauce_connect:
    username: "schapke"
    access_key: "8e2fbfef-01ac-4bd3-a7d9-e083eb0e4bbf"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
