# Generated by Django 2.1.7 on 2019-04-13 12:31

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
