# Generated by Django 2.1.7 on 2019-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='main',
            field=models.BooleanField(default=True),
        ),
    ]
