# Generated by Django 2.1.7 on 2019-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0002_auto_20190413_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
