# Generated by Django 2.1.7 on 2019-03-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0005_auto_20190324_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_images/'),
        ),
    ]
