# Generated by Django 2.1.7 on 2019-04-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0014_remove_item_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colors',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.TextField(default='[]'),
        ),
    ]
