# Generated by Django 2.1.7 on 2019-04-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0016_auto_20190403_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bagify.Color'),
        ),
    ]
