# Generated by Django 2.1.7 on 2019-04-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0020_auto_20190407_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_number',
            field=models.CharField(default='la', max_length=20),
            preserve_default=False,
        ),
    ]
