# Generated by Django 2.1.7 on 2019-04-08 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0021_address_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
