# Generated by Django 2.1.7 on 2019-04-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0024_auto_20190408_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='secondary_carousel/')),
                ('url', models.CharField(max_length=800, null=True)),
            ],
        ),
    ]
