# Generated by Django 2.1.7 on 2019-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagify', '0026_auto_20190411_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecondaryCarousel',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
