# Generated by Django 2.1.7 on 2019-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothStore', '0004_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_images'),
        ),
    ]
