# Generated by Django 2.1.7 on 2019-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothStore', '0007_auto_20190325_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='subtitle',
            field=models.CharField(default='tot', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(default='tot', max_length=50),
            preserve_default=False,
        ),
    ]
