# Generated by Django 2.1.7 on 2019-03-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothStore', '0009_auto_20190326_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='tes', upload_to='categories_images/'),
            preserve_default=False,
        ),
    ]
