# Generated by Django 2.1.7 on 2019-03-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothStore', '0011_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
