# Generated by Django 2.1.7 on 2019-04-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothStore', '0018_auto_20190404_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='main_image',
        ),
    ]
